[package]
name = "kiwmi"
version = "0.1.0"
authors = ["buffet <niclas@countingsort.com>"]
edition = "2018"

[dependencies]
log = "0.4"

[dependencies.wlroots]
path = "wlroots-rs"
features = ["static", "unstable"]
