[package]
name = "kiwmi"
version = "0.1.0"
authors = ["buffet <niclas@countingsort.com>"]
edition = "2018"

[dependencies]
env_logger = "0.6.0"
log = "0.4.0"

[dependencies.wlroots]
path = "wlroots-rs"
features = ["static", "unstable"]
